name: Release Note Automation

on:
  push:
    commits: 
    - '*'
  #   tags:
  #   - '*'
  release:
    type: created

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        id: get_release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          prefixes: fix, feat, chore

      - name: Write release notes
        uses: actions/checkout@v2
        with:
          content: |
            ## Changes
            ${{ steps.get_release.outputs.changes }}

      - name: Create or update release
        uses: actions/checkout@v2
        with:
          tag_name: ${{ steps.get_release.outputs.tag_name }}
          release_name: ${{ steps.get_release.outputs.tag_name }}
          draft: false
          prerelease: false
          body_path: release-notes.md
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release-Notes-Preview
        uses: snyk/release-notes-preview@v1.6.1
        with:
          releaseBranch: master
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


